CREATE TABLE "kill" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "kill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"matchId" varchar(255) NOT NULL,
	"frame" integer NOT NULL,
	"tick" integer NOT NULL,
	"roundNumber" integer NOT NULL,
	"weaponType" varchar(255) NOT NULL,
	"weaponName" varchar(255) NOT NULL,
	"killerName" varchar(255) NOT NULL,
	"killerSteamId" varchar(255) NOT NULL,
	"killerSide" integer NOT NULL,
	"killerTeamName" varchar(255) NOT NULL,
	"killerX" double precision NOT NULL,
	"killerY" double precision NOT NULL,
	"killerZ" double precision NOT NULL,
	"isKillerAirborne" boolean NOT NULL,
	"isKillerBlinded" boolean NOT NULL,
	"isKillerControllingBot" boolean NOT NULL,
	"victimName" varchar(255) NOT NULL,
	"victimSteamId" varchar(255) NOT NULL,
	"victimSide" integer NOT NULL,
	"victimTeamName" varchar(255) NOT NULL,
	"victimX" double precision NOT NULL,
	"victimY" double precision NOT NULL,
	"victimZ" double precision NOT NULL,
	"isVictimAirborne" boolean NOT NULL,
	"isVictimBlinded" boolean NOT NULL,
	"isVictimControllingBot" boolean NOT NULL,
	"isVictimInspectingWeapon" boolean NOT NULL,
	"assisterName" varchar(255),
	"assisterSteamId" varchar(255),
	"assisterSide" integer,
	"assisterTeamName" varchar(255),
	"assisterX" double precision,
	"assisterY" double precision,
	"assisterZ" double precision,
	"isAssisterControllingBot" boolean,
	"isAssistedFlash" boolean,
	"isHeadshot" boolean NOT NULL,
	"penetratedObjects" integer NOT NULL,
	"isThroughSmoke" boolean NOT NULL,
	"isNoScope" boolean NOT NULL,
	"isTradeKill" boolean NOT NULL,
	"isTradeDeath" boolean NOT NULL,
	"distance" double precision NOT NULL
);
--> statement-breakpoint
ALTER TABLE "kill" ADD CONSTRAINT "kill_matchId_match_id_fk" FOREIGN KEY ("matchId") REFERENCES "public"."match"("id") ON DELETE cascade ON UPDATE no action;